#!/bin/bash

# Setup script for Crew AI GCP deployment
# This script helps automate the initial setup process

set -e

echo "=========================================="
echo "Crew AI - GCP Setup Script"
echo "=========================================="
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    echo -e "${RED}Error: gcloud CLI is not installed${NC}"
    echo "Please install it from: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: Terraform is not installed${NC}"
    echo "Please install it from: https://developer.hashicorp.com/terraform/downloads"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites check passed${NC}"
echo ""

# Get project ID
echo "Enter your GCP Project ID:"
read -r PROJECT_ID

if [ -z "$PROJECT_ID" ]; then
    echo -e "${RED}Error: Project ID cannot be empty${NC}"
    exit 1
fi

echo ""
echo "Setting GCP project to: $PROJECT_ID"
gcloud config set project "$PROJECT_ID"

echo ""
echo "Do you want to enable required GCP APIs? (y/n)"
read -r ENABLE_APIS

if [ "$ENABLE_APIS" = "y" ]; then
    echo "Enabling required APIs..."
    gcloud services enable aiplatform.googleapis.com
    gcloud services enable run.googleapis.com
    gcloud services enable cloudbuild.googleapis.com
    gcloud services enable artifactregistry.googleapis.com
    echo -e "${GREEN}✓ APIs enabled${NC}"
fi

echo ""
echo "Enter your Serper API key (or press Enter to skip):"
read -r SERPER_KEY

echo ""
echo "Enter your preferred GCP region (default: us-central1):"
read -r REGION
REGION=${REGION:-us-central1}

# Create terraform.tfvars
echo ""
echo "Creating terraform/terraform.tfvars..."
cd terraform

cat > terraform.tfvars <<EOF
# Auto-generated by setup.sh

project_id = "$PROJECT_ID"
region     = "$REGION"

# Cloud Run Configuration
service_name = "crew-ai-travel-agent"
min_instances = 0
max_instances = 10
cpu_limit    = "2"
memory_limit = "2Gi"

# Set to true for testing, false for production
allow_unauthenticated = false

# Serper API Key
EOF

if [ -n "$SERPER_KEY" ]; then
    echo "serper_api_key = \"$SERPER_KEY\"" >> terraform.tfvars
else
    echo "# serper_api_key = \"your-key-here\"" >> terraform.tfvars
fi

echo -e "${GREEN}✓ terraform.tfvars created${NC}"

# Create .env file
echo ""
echo "Creating .env file..."
cd ..

cat > .env <<EOF
# Auto-generated by setup.sh

GCP_PROJECT_ID=$PROJECT_ID
GCP_LOCATION=$REGION
EOF

if [ -n "$SERPER_KEY" ]; then
    echo "SERPER_API_KEY=$SERPER_KEY" >> .env
else
    echo "# SERPER_API_KEY=your-key-here" >> .env
fi

echo -e "${GREEN}✓ .env created${NC}"

echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review and edit terraform/terraform.tfvars if needed"
echo "2. Run: cd terraform && terraform init"
echo "3. Run: terraform plan"
echo "4. Run: terraform apply"
echo "5. Build and deploy: gcloud builds submit --tag $REGION-docker.pkg.dev/$PROJECT_ID/crew-ai-images/crew-ai:latest"
echo ""
echo "See DEPLOYMENT.md for detailed instructions."
echo ""
